name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_PW: ${{ secrets.MYSQL_PW }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PW: ${{ secrets.DB_PW }}

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PW }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DB }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Create application.properties
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
        ls -al
      
    - name: Build with gradle
      run: |
        ./gradlew build

    - name: Stop and remove any existing containers
      run: |
        docker-compose down || true
        docker ps -q --filter "name=settlementsystem_" | grep -q . && docker stop $(docker ps -q --filter "name=settlementsystem_") || true
        docker ps -a -q --filter "name=settlementsystem_" | grep -q . && docker rm $(docker ps -a -q --filter "name=settlementsystem_") || true
        docker volume prune -f
        
    - name: Run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for services to be up
      run: sleep 30

    - name: Run tests
      run: ./gradlew test
